'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';

const demo=[{id:'demo-1',icon:'🥔',name:'Potatoes',price:15,unit:'kg',location:'Teyateyaneng',farmer:'Mpho Farm',category:'Vegetables',qty:'500 kg'},{id:'demo-2',icon:'🍅',name:'Tomatoes',price:18,unit:'kg',location:'Maseru',farmer:'Thaba Produce',category:'Vegetables',qty:'220 kg'},{id:'demo-3',icon:'🥚',name:'Fresh Eggs',price:65,unit:'tray',location:'Leribe',farmer:'Nala Poultry',category:'Livestock',qty:'80 trays'},{id:'demo-4',icon:'🌽',name:'Maize',price:9,unit:'kg',location:'Mafeteng',farmer:'Khotso Farm',category:'Grains',qty:'1,000 kg'}];

export default function Marketplace(){
 const [q,setQ]=useState(''); const [category,setCategory]=useState('All'); const [products,setProducts]=useState(demo); const [live,setLive]=useState(false);
 useEffect(()=>{(async()=>{if(!supabase)return;const {data,error}=await supabase.from('products').select('*, profiles(full_name)').eq('status','available').order('created_at',{ascending:false});if(!error&&data?.length){setProducts(data.map(p=>({id:p.id,name:p.name,price:p.price,unit:p.unit,location:p.location,farmer:p.profiles?.full_name||'AgriLink Farmer',category:p.category,qty:`${p.quantity} ${p.unit}`,description:p.description,icon:p.category==='Fruit'?'🍎':p.category==='Grains'?'🌽':p.category==='Livestock'?'🥚':'🌱'})));setLive(true);}})();},[]);
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.location} ${p.farmer}`.toLowerCase().includes(q.toLowerCase()))),[q,category,products]);
 return <main className="shell"><nav className="nav"><a className="brand" href="/">🌱 AgriLink</a><div className="navlinks"><a href="/marketplace">Marketplace</a><a href="/dashboard">Dashboard</a><a href="/about">How it works</a></div><a className="btn primary" href="/sell">Sell produce</a></nav><section className="section"><span className="badge">{live?'LIVE MARKETPLACE':'MARKETPLACE DEMO'}</span><h1>Find fresh produce</h1><p className="muted">Discover products from farmers around Lesotho.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search potatoes, eggs, Maseru..."/><a className="btn primary" href="#listings">Search</a></div><div className="actions">{['All','Vegetables','Fruit','Grains','Livestock'].map(c=><button className={'btn '+(category===c?'primary':'secondary')} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div id="listings" className="product-grid">{filtered.map(p=><article className="product" key={p.id}><div className="product-img">{p.icon}</div><div className="product-body"><span className="badge">{p.category}</span><h3>{p.name}</h3><p><b>M{p.price}</b> / {p.unit}</p><p>📍 {p.location} · {p.qty}</p><p>👨‍🌾 {p.farmer}</p><a className="btn primary" href={'/product/'+p.id}>View listing</a></div></article>)}</div>{filtered.length===0&&<div className="card" style={{marginTop:20}}>No listings match your search yet.</div>}</section></main>;
}
