'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

export default function SellPage(){
 const [user,setUser]=useState(null); const [form,setForm]=useState({name:'',category:'Vegetables',description:'',price:'',unit:'kg',quantity:'',location:''}); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{if(!supabase){setMessage('Connect Supabase first.');return;}const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/auth';return;}const {data:p}=await supabase.from('profiles').select('role,location').eq('id',user.id).single();if(p?.role!=='farmer'){setMessage('Only farmer accounts can create listings.');return;}setUser(user);if(p.location)setForm(f=>({...f,location:p.location}));})();},[]);
 function set(k,v){setForm(f=>({...f,[k]:v}));}
 async function submit(e){e.preventDefault();setMessage('');if(!supabase||!user)return;setBusy(true);try{const payload={farmer_id:user.id,name:form.name,category:form.category,description:form.description,price:Number(form.price),unit:form.unit,quantity:Number(form.quantity),location:form.location,status:'available'};const {error}=await supabase.from('products').insert(payload);if(error)throw error;setMessage('Your produce is now listed on AgriLink.');setForm(f=>({...f,name:'',description:'',price:'',quantity:''}));}catch(err){setMessage(err.message||'Could not create listing.');}finally{setBusy(false);}}
 return <main className="shell"><nav className="nav"><a className="brand" href="/">🌱 AgriLink</a><div className="navlinks"><a href="/marketplace">Marketplace</a><a href="/dashboard">Dashboard</a></div></nav><section className="section form-wrap"><span className="badge">SELL PRODUCE</span><h1>List what you grow</h1><p className="muted">Tell buyers what you have available, how much it costs and where they can find you.</p><form className="card form-grid" onSubmit={submit}><label>Product name<input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Potatoes"/></label><label>Category<select value={form.category} onChange={e=>set('category',e.target.value)}><option>Vegetables</option><option>Fruit</option><option>Grains</option><option>Livestock</option><option>Dairy</option><option>Other</option></select></label><label>Price (M)<input required min="0" step="0.01" type="number" value={form.price} onChange={e=>set('price',e.target.value)} placeholder="15"/></label><label>Unit<select value={form.unit} onChange={e=>set('unit',e.target.value)}><option>kg</option><option>ton</option><option>tray</option><option>box</option><option>head</option><option>litre</option><option>piece</option></select></label><label>Quantity available<input required min="0" step="0.01" type="number" value={form.quantity} onChange={e=>set('quantity',e.target.value)} placeholder="500"/></label><label>Location<input required value={form.location} onChange={e=>set('location',e.target.value)} placeholder="Teyateyaneng"/></label><label className="full">Description<textarea rows="5" value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Freshly harvested, pickup available..."/></label><button className="btn primary" disabled={busy}>{busy?'Publishing...':'Publish listing'}</button>{message&&<div className="notice full">{message}</div>}</form></section></main>;
}
