const products={
 '1':{icon:'🥔',name:'Potatoes',price:'M15 / kg',location:'Teyateyaneng',farmer:'Mpho Farm',qty:'500 kg',description:'Fresh local potatoes available for pickup. Bulk orders welcome.'},
 '2':{icon:'🍅',name:'Tomatoes',price:'M18 / kg',location:'Maseru',farmer:'Thaba Produce',qty:'220 kg',description:'Fresh tomatoes for households, shops and restaurants.'},
 '3':{icon:'🥚',name:'Fresh Eggs',price:'M65 / tray',location:'Leribe',farmer:'Nala Poultry',qty:'80 trays',description:'Fresh farm eggs available in trays.'},
 '4':{icon:'🌽',name:'Maize',price:'M9 / kg',location:'Mafeteng',farmer:'Khotso Farm',qty:'1,000 kg',description:'Bulk maize for households and businesses.'},
 '5':{icon:'🥬',name:'Cabbage',price:'M12 / head',location:'Maseru',farmer:'Makoanyane Farm',qty:'350 heads',description:'Fresh cabbage harvested locally.'},
 '6':{icon:'🍓',name:'Strawberries',price:'M55 / box',location:'Roma',farmer:'Roma Fresh',qty:'60 boxes',description:'Fresh strawberries in ready-to-buy boxes.'}
};
export default async function Product({params}){const p=products[params.id]||products['1'];return <main className="shell"><nav className="nav"><a className="brand" href="/">🌱 AgriLink</a><div className="navlinks"><a href="/marketplace">Marketplace</a><a href="/sell">Sell</a></div></nav><section className="section"><a href="/marketplace">← Back to marketplace</a><div className="hero-card" style={{marginTop:24,maxWidth:850}}><div className="product-img" style={{borderRadius:18}}>{p.icon}</div><span className="badge" style={{marginTop:20}}>AVAILABLE</span><h1>{p.name}</h1><h2 className="price">{p.price}</h2><p>📍 {p.location} · {p.qty}</p><p>👨‍🌾 Sold by <b>{p.farmer}</b></p><p className="muted">{p.description}</p><div className="actions"><a className="btn primary" href={'mailto:?subject=AgriLink%20order%20for%20'+encodeURIComponent(p.name)}>Contact farmer</a><a className="btn secondary" href="/marketplace">Find more produce</a></div></div></section></main>}
