'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

export default function Dashboard() {
  const [user,setUser]=useState(null); const [profile,setProfile]=useState(null); const [products,setProducts]=useState([]); const [message,setMessage]=useState('Loading...');
  useEffect(()=>{ (async()=>{ if(!supabase){setMessage('Connect Supabase to use your dashboard.');return;} const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href='/auth';return;} setUser(user); const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).single(); setProfile(p); if(p?.role==='farmer'){const {data:list}=await supabase.from('products').select('*').eq('farmer_id',user.id).order('created_at',{ascending:false});setProducts(list||[]);} setMessage(''); })(); },[]);
  async function logout(){await supabase?.auth.signOut();window.location.href='/';}
  return <main className="shell"><nav className="nav"><a className="brand" href="/">🌱 AgriLink</a><div className="navlinks"><a href="/marketplace">Marketplace</a>{profile?.role==='farmer'&&<a href="/sell">Sell</a>}</div><button className="btn secondary" onClick={logout}>Sign out</button></nav><section className="section"><span className="badge">DASHBOARD</span><h1>Hello{profile?.full_name ? ', '+profile.full_name : ''} 👋</h1><p className="muted">{profile?.role==='farmer'?'Manage your produce listings.':'Find produce from farmers around Lesotho.'}</p>{message&&<div className="notice">{message}</div>}{profile?.role==='farmer'&&<><div className="actions"><a className="btn primary" href="/sell">＋ Add produce</a><a className="btn secondary" href="/marketplace">Browse marketplace</a></div><div className="product-grid">{products.map(p=><article className="product" key={p.id}><div className="product-img">🌱</div><div className="product-body"><span className="badge">{p.status}</span><h3>{p.name}</h3><p><b>M{p.price}</b> / {p.unit}</p><p>{p.quantity} {p.unit} · 📍 {p.location}</p></div></article>)}{products.length===0&&!message&&<div className="card">You have no listings yet. Add your first product.</div>}</div></>}{profile?.role==='buyer'&&<div className="card" style={{marginTop:24}}><h2>Ready to buy?</h2><p className="muted">Search available produce and contact farmers directly.</p><a className="btn primary" href="/marketplace">Open marketplace</a></div>}</section></main>;
}
